### PR TITLE
Update versions

### PR DESCRIPTION
**Pull request by jaredsburrows**

### CODE REVIEW

**Comment by jaredsburrows** [comment]
Let me fix this and I will update the PR soon.

**Comment by benjamin-bader** [comment]
...looks like our Travis job needs to be updated to accept new Android SDK licenses?

**Comment by jaredsburrows** [comment]
Yes

**Comment by benjamin-bader** [comment]
Travis _should_ be fixed now as of #228; I just restarted this PR's build, so cross your fingers!

**Comment by benjamin-bader** [comment]
d'oh, I'm dumb, this PR needs to be rebased off of master.

**Comment by jaredsburrows** [comment]
Updated the travis ci

**Comment by jaredsburrows** [comment]
@benjamin-bader Can you review this and merge? It should permanently fix the update issues.

**Comment by jaredsburrows** [comment]
@benjamin-bader Build passed!

**Comment by benjamin-bader** [comment]
Awesome fix for Travis - thanks!

**Pull request merged**
