### PR TITLE
Add Team City integration

### PR DESCRIPTION
**Pull request by ckesc**
Adds integration with Team City statistic page. (like existing integration with Jenkins Plot Plugin)
Just prints lines in specific format
[Docs](https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingBuildStatistics)

### CODE REVIEW

**Comment by benjamin-bader** [comment]
Looks super simple and worthwhile.

For my own reference, the format for a build stat is:
`##teamcity[buildStatisticValue key='<valueTypeKey>' value='<value>']`

These need to be printed to stdout; we can optionally do so as configured.  We'll tentatively settle on `dexcountMethods` and `dexcountFields` as the stat keys, unless there's a problem with that.

**Comment by ckesc** [comment]
Yes. Also I compose key names unique for every variant in format like `DexCount_universalDebug_MethodCount`
So, shall I fix something? Or everything is ok?

**Comment by benjamin-bader** [comment]
I mean, if you want to do this I'd be happy to take a PR; if not, I'll get around to it sooner or later.  Agree that the stat name should contain the variant name, good point.

**Comment by karlicoss** [comment]
@benjamin-bader I think you were confused somehow. This is a PR, not an issue, @ckesc has already implemented everything you mentioned :D

**Comment by benjamin-bader** [comment]
OMG - you're absolutely right!  Sorry, @ckesc, I'll look now.

**Comment by benjamin-bader** [comment]
Thanks for the contribution!

**Comment by karlicoss** [comment]
:D

**Pull request merged**
