### PR TITLE
Check if the file exists before trying to extract a DexFile. If it doesn't exist just return an empty array.

### PR DESCRIPTION
**Pull request by fcduarte**

### CODE REVIEW

**Comment by benjamin-bader** [comment]
Thanks!  You mentioned in #137 that, with this fix, the non-existing artifacts are printed out as having 0 methods and fields.  I think it should be possible to skip printing anything at all in the task itself - I'm thinking that in `DexMethodCountTask#countMethods()`, we may just be able to check `apkOrDex.output?.exists()` and end the task early if it doesn't.

That way, we won't be doing the extra work of counting nothing :)

**Comment by fcduarte** [comment]
I'll try. Should I keep the check at `DexFile` as a protection or should I remove it?

**Comment by fcduarte** [comment]
@benjamin-bader please review it again

**Comment by benjamin-bader** [comment]
Thanks, @fcduarte - looks great!

**Comment by fcduarte** [comment]
@benjamin-bader thanks for merging! Any plans to release it? I had to comment out the plugin at my project :\ .. Just waiting for the fix!

**Comment by benjamin-bader** [comment]
Just release 0.6.2 to Maven Central; should be available within the next 10-15 minutes.

**Pull request merged**
