### PR TITLE
Update to Gradle 2.14

### PR DESCRIPTION
**Pull request by iamstuffed**
This updates the plugin to support Gradle 2.14. 

```.buildscript/test.sh
:clean UP-TO-DATE
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
:compileGroovy
:processResources
:classes
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResources
:testClasses
:test
:check
:groovydoc
Trying to override old definition of task fileScanner
:groovydocJar
:jar
:javadoc
:javadocJar
:sourcesJar
:signArchives SKIPPED
:install

BUILD SUCCESSFUL

Total time: 1 mins 18.126 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html
Building integration test project...
Integration build done!  Running tests...
Total methods in app-debug.apk: 16174 (24.68% used)
Total fields in app-debug.apk:  7093 (10.82% used)
Methods remaining in app-debug.apk: 49361
Fields remaining in app-debug.apk:  58442
Total methods in tests-debug.apk: 3085 (4.71% used)
Total fields in tests-debug.apk:  774 (1.18% used)
Methods remaining in tests-debug.apk: 62450
Fields remaining in tests-debug.apk:  64761
Tests complete.```

### CODE REVIEW

**Comment by benjamin-bader** [comment]
Hi, thanks for your contribution!

I actually just landed #110 which does some of this.  It doesn't contain the `StyledTextOutput` changes though, as I hadn't noticed any problems so far.  I did notice that this interface has been deprecated.  Have you seen issues with output using 2.14?

**Comment by iamstuffed** [comment]
I only ever check text output when building and the html chart and it seems fine. I mainly did this quickly when the 2.14 RC versions were available and kept it up to date and finally did a pull request since it has been released. I realize this won't be backwards compatible.

**Comment by benjamin-bader** [comment]
OK, thanks for that.  It looks like we're fine as-is on 2.14 and below, so there's no need to refactor `StyledTextOutput` usage; I'm going to close this PR without merging, since the rest of the changes landed separately.  I appreciate the effort you put in!

**Comment by iamstuffed** [comment]
I'll check later today. Your integration project uses 2.12, so won't show any errors, I think.

I made these changes because I am using it in a project that uses 2.14.

**Comment by benjamin-bader** [comment]
True, I should add another.  I manually verified that it worked with 2.14, but if I missed something please do let me know.

**Pull request closed without merging**
